[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
og_chain = "${OG_CHAIN_RPC}"
og_testnet = "https://evmrpc-testnet.0g.ai"

[etherscan]
og_testnet = { key = "no-key-needed", url = "https://chainscan-galileo.0g.ai/open/api/", chain = 16602 }
